In [1]:
import numpy as np
import cvxpy as cvx

In [47]:
# exercise 1
f = np.array([[2],[3]])

lb = np.array([[1],[2]])

A = np.array([[2,2],[1,2]])
b = np.array([[20],[14]])

x = cvx.Variable([2,1])

obj = cvx.Minimize(-f.T @ x)


constraints = [A@x <= b, lb <= x]

prob = cvx.Problem(obj, constraints)
result = prob.solve()

print(x.value)
print(result)

[[6.]
 [4.]]
-23.999999999256048


In [44]:
# exercise 2
f = np.array([[1],[2]])
H = np.array([[1/2,0],[0,0]])
lb = np.array([[0],[0]])

A = np.array([[-2,-3],[3,4],[2,4]])
b = np.array([[12,80,80]])

x = cvx.Variable([2,1])

obj = cvx.Minimize(cvx.quad_form(x,H)+-f.T @ x)

constraints = [A@x <= b, lb <= x]

prob = cvx.Problem(obj, constraints)
result = prob.solve()

print(x.value)
print(result)

[[3.50395108e-18]
 [3.00000000e+00]]
-6.0


In [43]:
# exercise 3
H = np.matrix([[5,-1],[-1,5]])
g = -np.matrix([[-4],[4]])

x = np.zeros(shape = (2,1))
alpha = 0.2

for i in range(100):
    df = H.T*x+H*x+g
    x = x - alpha * df
    
print(x)

[[ 1.3667287e+14]
 [-1.3667287e+14]]
