In [2]:
import tensorflow as tf
import numpy as np

In [15]:
# 데이터 타입 맞춰 줘야 함

score = tf.constant([[58,11,94,87,62],[64,79,91,35,57],[78,80,96,74,83]], dtype = tf.dtypes.float32)
c = tf.constant([0.2,0.3,0.5])
print(score)

c =tf.expand_dims(c,axis =1)
print(c)

score * c 

tf.Tensor(
[[58. 11. 94. 87. 62.]
 [64. 79. 91. 35. 57.]
 [78. 80. 96. 74. 83.]], shape=(3, 5), dtype=float32)
tf.Tensor(
[[0.2]
 [0.3]
 [0.5]], shape=(3, 1), dtype=float32)


<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[11.6     ,  2.2     , 18.800001, 17.4     , 12.400001],
       [19.2     , 23.7     , 27.300001, 10.5     , 17.1     ],
       [39.      , 40.      , 48.      , 37.      , 41.5     ]],
      dtype=float32)>