In [2]:
# for문

In [3]:
for i in range(1,10):
    for k in range(1, 10):
        result = i*k
        print(i,'X',k,'=',result)
    print('\n')

1 X 1 = 1
1 X 2 = 2
1 X 3 = 3
1 X 4 = 4
1 X 5 = 5
1 X 6 = 6
1 X 7 = 7
1 X 8 = 8
1 X 9 = 9


2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18


3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27


4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36


5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45


6 X 1 = 6
6 X 2 = 12
6 X 3 = 18
6 X 4 = 24
6 X 5 = 30
6 X 6 = 36
6 X 7 = 42
6 X 8 = 48
6 X 9 = 54


7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 63


8 X 1 = 8
8 X 2 = 16
8 X 3 = 24
8 X 4 = 32
8 X 5 = 40
8 X 6 = 48
8 X 7 = 56
8 X 8 = 64
8 X 9 = 72


9 X 1 = 9
9 X 2 = 18
9 X 3 = 27
9 X 4 = 36
9 X 5 = 45
9 X 6 = 54
9 X 7 = 63
9 X 8 = 72
9 X 9 = 81




In [4]:
# panda

In [6]:
import pandas as pd

data = {"name_id_code":['0','105','12','130'],
        "year":[2014,2015,2016,2017],
        "points":[10,15,30,5],
        "penalty":[1,2,5,0]}

df = pd.DataFrame(data, columns = ['year','name_id_code','points','penalty'], index = ['1','2','3','4'])

df

year name_id_code  points  penalty
1  2014            0      10        1
2  2015          105      15        2
3  2016           12      30        5
4  2017          130       5        0

In [23]:
#exercise 1

import numpy as np

A =  np.array([[7,-2,1],[-1,3,0],[8,-2,4]])
b = np.array([10,5,3])

np.linalg.inv(A).dot(b)

# A=np.asmatrix(A)
# b=np.asmatrix(b)

# x = A.I * b

array([ 2.61111111,  2.53703704, -3.2037037 ])

In [12]:
# exercise 2,3

x = np.array([[1],[1]])
y = np.array([[2],[3]])

x.T.dot(y)

array([[5]])

In [16]:
# exercise 4
A = np.array([[4,1],[3,2],[1,3]])
B = np.array([[2],[1],[0]])

X = np.linalg.inv((A.T.dot(A))).dot(A.T).dot(B)

print(X)

# 검증 A X^* = B^*

[[ 0.52307692]
 [-0.2       ]]
